// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_4u85EtcD04FJ6PUCHE_yZgpAoR1D1g',
    appId: '1:540943160939:web:7e81bf9f8e5b25334a032e',
    messagingSenderId: '540943160939',
    projectId: 'v-serve-arta-feedback-survey',
    authDomain: 'v-serve-arta-feedback-survey.firebaseapp.com',
    storageBucket: 'v-serve-arta-feedback-survey.firebasestorage.app',
    measurementId: 'G-PNY4KJFLCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQg9JQgEobBgqn_xLBovJwjW49_84gKgg',
    appId: '1:540943160939:android:bd96ffa0e2e411054a032e',
    messagingSenderId: '540943160939',
    projectId: 'v-serve-arta-feedback-survey',
    storageBucket: 'v-serve-arta-feedback-survey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTUeGdTTyHOGzIZ28yX7gTPb4mH2SFLY',
    appId: '1:540943160939:ios:2274d33268c2d26d4a032e',
    messagingSenderId: '540943160939',
    projectId: 'v-serve-arta-feedback-survey',
    storageBucket: 'v-serve-arta-feedback-survey.firebasestorage.app',
    iosBundleId: 'com.example.artaCss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTUeGdTTyHOGzIZ28yX7gTPb4mH2SFLY',
    appId: '1:540943160939:ios:2274d33268c2d26d4a032e',
    messagingSenderId: '540943160939',
    projectId: 'v-serve-arta-feedback-survey',
    storageBucket: 'v-serve-arta-feedback-survey.firebasestorage.app',
    iosBundleId: 'com.example.artaCss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_4u85EtcD04FJ6PUCHE_yZgpAoR1D1g',
    appId: '1:540943160939:web:13abf6727945bd0d4a032e',
    messagingSenderId: '540943160939',
    projectId: 'v-serve-arta-feedback-survey',
    authDomain: 'v-serve-arta-feedback-survey.firebaseapp.com',
    storageBucket: 'v-serve-arta-feedback-survey.firebasestorage.app',
    measurementId: 'G-TS999638DG',
  );
}
